@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Batch\obj\Release\Batch.dll" "C:\Cryptography\Mark Three Software\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Configuration Sections\obj\Release\Configuration Sections.dll" "C:\Cryptography\Mark Three Software\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Core Service\obj\Release\Core Service.dll" "C:\Cryptography\Mark Three Software\Guardian\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\External Service\obj\Release\External Service.dll" "C:\Cryptography\Mark Three Software\Guardian\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Guardian Library\obj\Release\Guardian Library.dll" "C:\Cryptography\Mark Three Software\Guardian\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Mark Three Library\obj\Release\Mark Three Library.dll"  "C:\Cryptography\Mark Three Software\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Market Data\obj\Release\Market Data.dll" "C:\Cryptography\Mark Three Software\Guardian\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Matching Service\obj\Release\Matching Service.dll" "C:\Cryptography\Mark Three Software\Guardian\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Price Simulator\obj\Release\Price Simulator.dll" "C:\Cryptography\Mark Three Software\Guardian\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Real Time Pricing\obj\Release\Real Time Pricing.dll" "C:\Cryptography\Mark Three Software\Guardian\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Real Time Pricing\obj\Release\AxDBCCTRLLib.dll" "C:\Cryptography\Mark Three Software\Guardian\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Real Time Pricing\obj\Release\DBCCTRLLib.dll" "C:\Cryptography\Mark Three Software\Guardian\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Server Market Data\obj\Release\Server Market Data.dll" "C:\Cryptography\Mark Three Software\Guardian\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Trading Service\obj\Release\Trading Service.dll" "C:\Cryptography\Mark Three Software\Guardian\Key Pair.snk"
@sn -q -R "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Web Transaction\obj\Release\Web Transaction.dll" "C:\Cryptography\Mark Three Software\Key Pair.snk" 
