//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkThree.Guardian.Core
{
    using MarkThree.Guardian;
    using MarkThree.Guardian.Server;
    using MarkThree;
    using System;
    using System.Collections;
    using System.Data;
    using System.Data.SqlClient;
    
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    public class SourceOrder
    {
        
        /// This value is used to map the object to a persistent storage device.  The parameters for the storage
        /// are found in the configuration file for this service.
        public static string PersistentStore = "Guardian";
        
        /// This member provides access to the in-memory database.
        private static ServerMarketData serverMarketData = new ServerMarketData();
        
        /// <summary>Collects the table lock request(s) for an Insert operation</summary>
        /// <param name="adoTransaction">A list of locks required for this operation.</param>
        public static void Insert(AdoTransaction adoTransaction)
        {
            // These table lock(s) are required for this operation.
            adoTransaction.LockRequests.AddWriterLock(ServerMarketData.SourceOrderLock);
        }
        
        /// <summary>Inserts a SourceOrder record using Metadata Parameters.</summary>
        /// <param name="parameters">Contains the metadata parameters.</param>
        public static void Insert(ParameterList parameters)
        {
            // Extract the parameters from the command batch.
            AdoTransaction adoTransaction = parameters["adoTransaction"];
            SqlTransaction sqlTransaction = parameters["sqlTransaction"];
            System.DateTime createdTime = parameters["createdTime"];
            int createdUserId = parameters["createdUserId"];
            object destinationId = parameters["destinationId"].Value;
            object externalId0 = parameters["externalId0"].Value;
            object isAdvertised = parameters["isAdvertised"].Value;
            object isAutoExecute = parameters["isAutoExecute"].Value;
            object isCanceled = parameters["isCanceled"].Value;
            object isHeld = parameters["isHeld"].Value;
            object isSteppedIn = parameters["isSteppedIn"].Value;
            object isSubmitted = parameters["isSubmitted"].Value;
            object limitPrice = parameters["limitPrice"].Value;
            object maximumVolatility = parameters["maximumVolatility"].Value;
            System.DateTime modifiedTime = parameters["modifiedTime"];
            int modifiedUserId = parameters["modifiedUserId"];
            object newsFreeTime = parameters["newsFreeTime"].Value;
            int orderTypeCode = parameters["orderTypeCode"];
            decimal orderedQuantity = parameters["orderedQuantity"];
            int priceTypeCode = parameters["priceTypeCode"];
            object receivedTime = parameters["receivedTime"].Value;
            int securityId = parameters["securityId"];
            object settlementId = parameters["settlementId"].Value;
            object startTime = parameters["startTime"].Value;
            int statusCode = parameters["statusCode"];
            object stopPrice = parameters["stopPrice"].Value;
            object stopTime = parameters["stopTime"].Value;
            object submittedQuantity = parameters["submittedQuantity"].Value;
            object submittedTime = parameters["submittedTime"].Value;
            object targetPrice = parameters["targetPrice"].Value;
            int timeInForceCode = parameters["timeInForceCode"];
            int workingOrderId = parameters["workingOrderId"];
            // The rowVersion is passed back to the caller in the event it's needed for additional commands in the batch.
            long rowVersion = long.MinValue;
            // Call the internal method to complete the operation.
            int sourceOrderId = SourceOrder.Insert(adoTransaction, sqlTransaction, ref rowVersion, createdTime, createdUserId, destinationId, externalId0, isAdvertised, isAutoExecute, isCanceled, isHeld, isSteppedIn, isSubmitted, limitPrice, maximumVolatility, modifiedTime, modifiedUserId, newsFreeTime, orderTypeCode, orderedQuantity, priceTypeCode, receivedTime, securityId, settlementId, startTime, statusCode, stopPrice, stopTime, submittedQuantity, submittedTime, targetPrice, timeInForceCode, workingOrderId);
            // Return values.
            parameters["rowVersion"] = rowVersion;
            parameters.Return = sourceOrderId;
        }
        
        /// <summary>Inserts a SourceOrder record.</summary>
        /// <param name="transaction">Commits or rejects a set of commands as a unit</param>
        /// <param name="createdTime">The value for the CreatedTime column.</param>
        /// <param name="createdUserId">The value for the CreatedUserId column.</param>
        /// <param name="destinationId">The value for the DestinationId column.</param>
        /// <param name="externalId0">The value for the ExternalId0 column.</param>
        /// <param name="isAdvertised">The value for the IsAdvertised column.</param>
        /// <param name="isAutoExecute">The value for the IsAutoExecute column.</param>
        /// <param name="isCanceled">The value for the IsCanceled column.</param>
        /// <param name="isHeld">The value for the IsHeld column.</param>
        /// <param name="isSteppedIn">The value for the IsSteppedIn column.</param>
        /// <param name="isSubmitted">The value for the IsSubmitted column.</param>
        /// <param name="limitPrice">The value for the LimitPrice column.</param>
        /// <param name="maximumVolatility">The value for the MaximumVolatility column.</param>
        /// <param name="modifiedTime">The value for the ModifiedTime column.</param>
        /// <param name="modifiedUserId">The value for the ModifiedUserId column.</param>
        /// <param name="newsFreeTime">The value for the NewsFreeTime column.</param>
        /// <param name="orderTypeCode">The value for the OrderTypeCode column.</param>
        /// <param name="orderedQuantity">The value for the OrderedQuantity column.</param>
        /// <param name="priceTypeCode">The value for the PriceTypeCode column.</param>
        /// <param name="receivedTime">The value for the ReceivedTime column.</param>
        /// <param name="securityId">The value for the SecurityId column.</param>
        /// <param name="settlementId">The value for the SettlementId column.</param>
        /// <param name="startTime">The value for the StartTime column.</param>
        /// <param name="statusCode">The value for the StatusCode column.</param>
        /// <param name="stopPrice">The value for the StopPrice column.</param>
        /// <param name="stopTime">The value for the StopTime column.</param>
        /// <param name="submittedQuantity">The value for the SubmittedQuantity column.</param>
        /// <param name="submittedTime">The value for the SubmittedTime column.</param>
        /// <param name="targetPrice">The value for the TargetPrice column.</param>
        /// <param name="timeInForceCode">The value for the TimeInForceCode column.</param>
        /// <param name="workingOrderId">The value for the WorkingOrderId column.</param>
        public static int Insert(
                    AdoTransaction adoTransaction, 
                    SqlTransaction sqlTransaction, 
                    ref long rowVersion, 
                    System.DateTime createdTime, 
                    int createdUserId, 
                    object destinationId, 
                    object externalId0, 
                    object isAdvertised, 
                    object isAutoExecute, 
                    object isCanceled, 
                    object isHeld, 
                    object isSteppedIn, 
                    object isSubmitted, 
                    object limitPrice, 
                    object maximumVolatility, 
                    System.DateTime modifiedTime, 
                    int modifiedUserId, 
                    object newsFreeTime, 
                    int orderTypeCode, 
                    decimal orderedQuantity, 
                    int priceTypeCode, 
                    object receivedTime, 
                    int securityId, 
                    object settlementId, 
                    object startTime, 
                    int statusCode, 
                    object stopPrice, 
                    object stopTime, 
                    object submittedQuantity, 
                    object submittedTime, 
                    object targetPrice, 
                    int timeInForceCode, 
                    int workingOrderId)
        {
            // Accessor for the SourceOrder Table.
            ServerMarketData.SourceOrderDataTable sourceOrderTable = ServerMarketData.SourceOrder;
            // Apply Defaults
            if ((destinationId == null))
            {
                destinationId = System.DBNull.Value;
            }
            if ((externalId0 == null))
            {
                externalId0 = System.DBNull.Value;
            }
            if ((isAdvertised == null))
            {
                isAdvertised = false;
            }
            if ((isAutoExecute == null))
            {
                isAutoExecute = false;
            }
            if ((isCanceled == null))
            {
                isCanceled = false;
            }
            if ((isHeld == null))
            {
                isHeld = false;
            }
            if ((isSteppedIn == null))
            {
                isSteppedIn = false;
            }
            if ((isSubmitted == null))
            {
                isSubmitted = false;
            }
            if ((limitPrice == null))
            {
                limitPrice = System.DBNull.Value;
            }
            if ((maximumVolatility == null))
            {
                maximumVolatility = System.DBNull.Value;
            }
            if ((newsFreeTime == null))
            {
                newsFreeTime = System.DBNull.Value;
            }
            if ((receivedTime == null))
            {
                receivedTime = System.DBNull.Value;
            }
            if ((settlementId == null))
            {
                settlementId = System.DBNull.Value;
            }
            if ((startTime == null))
            {
                startTime = System.DBNull.Value;
            }
            if ((stopPrice == null))
            {
                stopPrice = System.DBNull.Value;
            }
            if ((stopTime == null))
            {
                stopTime = System.DBNull.Value;
            }
            if ((submittedQuantity == null))
            {
                submittedQuantity = 0.0m;
            }
            if ((submittedTime == null))
            {
                submittedTime = System.DBNull.Value;
            }
            if ((targetPrice == null))
            {
                targetPrice = System.DBNull.Value;
            }
            // Increment the row version
            rowVersion = ServerMarketData.RowVersion.Increment();
            // Insert the record into the ADO database.
            ServerMarketData.SourceOrderRow sourceOrderRow = sourceOrderTable.NewSourceOrderRow();
            sourceOrderRow[sourceOrderTable.RowVersionColumn] = rowVersion;
            sourceOrderRow[sourceOrderTable.CreatedTimeColumn] = createdTime;
            sourceOrderRow[sourceOrderTable.CreatedUserIdColumn] = createdUserId;
            sourceOrderRow[sourceOrderTable.DestinationIdColumn] = destinationId;
            sourceOrderRow[sourceOrderTable.ExternalId0Column] = externalId0;
            sourceOrderRow[sourceOrderTable.IsAdvertisedColumn] = isAdvertised;
            sourceOrderRow[sourceOrderTable.IsAutoExecuteColumn] = isAutoExecute;
            sourceOrderRow[sourceOrderTable.IsCanceledColumn] = isCanceled;
            sourceOrderRow[sourceOrderTable.IsHeldColumn] = isHeld;
            sourceOrderRow[sourceOrderTable.IsSteppedInColumn] = isSteppedIn;
            sourceOrderRow[sourceOrderTable.IsSubmittedColumn] = isSubmitted;
            sourceOrderRow[sourceOrderTable.LimitPriceColumn] = limitPrice;
            sourceOrderRow[sourceOrderTable.MaximumVolatilityColumn] = maximumVolatility;
            sourceOrderRow[sourceOrderTable.ModifiedTimeColumn] = modifiedTime;
            sourceOrderRow[sourceOrderTable.ModifiedUserIdColumn] = modifiedUserId;
            sourceOrderRow[sourceOrderTable.NewsFreeTimeColumn] = newsFreeTime;
            sourceOrderRow[sourceOrderTable.OrderTypeCodeColumn] = orderTypeCode;
            sourceOrderRow[sourceOrderTable.OrderedQuantityColumn] = orderedQuantity;
            sourceOrderRow[sourceOrderTable.PriceTypeCodeColumn] = priceTypeCode;
            sourceOrderRow[sourceOrderTable.ReceivedTimeColumn] = receivedTime;
            sourceOrderRow[sourceOrderTable.SecurityIdColumn] = securityId;
            sourceOrderRow[sourceOrderTable.SettlementIdColumn] = settlementId;
            sourceOrderRow[sourceOrderTable.StartTimeColumn] = startTime;
            sourceOrderRow[sourceOrderTable.StatusCodeColumn] = statusCode;
            sourceOrderRow[sourceOrderTable.StopPriceColumn] = stopPrice;
            sourceOrderRow[sourceOrderTable.StopTimeColumn] = stopTime;
            sourceOrderRow[sourceOrderTable.SubmittedQuantityColumn] = submittedQuantity;
            sourceOrderRow[sourceOrderTable.SubmittedTimeColumn] = submittedTime;
            sourceOrderRow[sourceOrderTable.TargetPriceColumn] = targetPrice;
            sourceOrderRow[sourceOrderTable.TimeInForceCodeColumn] = timeInForceCode;
            sourceOrderRow[sourceOrderTable.WorkingOrderIdColumn] = workingOrderId;
            sourceOrderTable.AddSourceOrderRow(sourceOrderRow);
            adoTransaction.DataRows.Add(sourceOrderRow);
            // Insert the record into the SQL database.
            SqlCommand sqlCommand = new SqlCommand(@"insert ""SourceOrder"" (""rowVersion"",""CreatedTime"",""CreatedUserId"",""DestinationId"",""ExternalId0"",""IsAdvertised"",""IsAutoExecute"",""IsCanceled"",""IsHeld"",""IsSteppedIn"",""IsSubmitted"",""LimitPrice"",""MaximumVolatility"",""ModifiedTime"",""ModifiedUserId"",""NewsFreeTime"",""OrderTypeCode"",""OrderedQuantity"",""PriceTypeCode"",""ReceivedTime"",""SecurityId"",""SettlementId"",""SourceOrderId"",""StartTime"",""StatusCode"",""StopPrice"",""StopTime"",""SubmittedQuantity"",""SubmittedTime"",""TargetPrice"",""TimeInForceCode"",""WorkingOrderId"") values (@rowVersion,@createdTime,@createdUserId,@destinationId,@externalId0,@isAdvertised,@isAutoExecute,@isCanceled,@isHeld,@isSteppedIn,@isSubmitted,@limitPrice,@maximumVolatility,@modifiedTime,@modifiedUserId,@newsFreeTime,@orderTypeCode,@orderedQuantity,@priceTypeCode,@receivedTime,@securityId,@settlementId,@sourceOrderId,@startTime,@statusCode,@stopPrice,@stopTime,@submittedQuantity,@submittedTime,@targetPrice,@timeInForceCode,@workingOrderId)");
            sqlCommand.Connection = sqlTransaction.Connection;
            sqlCommand.Transaction = sqlTransaction;
            sqlCommand.Parameters.Add(new SqlParameter("@rowVersion", SqlDbType.BigInt, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, rowVersion));
            sqlCommand.Parameters.Add(new SqlParameter("@createdTime", SqlDbType.DateTime, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, createdTime));
            sqlCommand.Parameters.Add(new SqlParameter("@createdUserId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, createdUserId));
            sqlCommand.Parameters.Add(new SqlParameter("@destinationId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, destinationId));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId0", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId0));
            sqlCommand.Parameters.Add(new SqlParameter("@isAdvertised", SqlDbType.Bit, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, isAdvertised));
            sqlCommand.Parameters.Add(new SqlParameter("@isAutoExecute", SqlDbType.Bit, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, isAutoExecute));
            sqlCommand.Parameters.Add(new SqlParameter("@isCanceled", SqlDbType.Bit, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, isCanceled));
            sqlCommand.Parameters.Add(new SqlParameter("@isHeld", SqlDbType.Bit, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, isHeld));
            sqlCommand.Parameters.Add(new SqlParameter("@isSteppedIn", SqlDbType.Bit, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, isSteppedIn));
            sqlCommand.Parameters.Add(new SqlParameter("@isSubmitted", SqlDbType.Bit, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, isSubmitted));
            sqlCommand.Parameters.Add(new SqlParameter("@limitPrice", SqlDbType.Decimal, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, limitPrice));
            sqlCommand.Parameters.Add(new SqlParameter("@maximumVolatility", SqlDbType.Decimal, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, maximumVolatility));
            sqlCommand.Parameters.Add(new SqlParameter("@modifiedTime", SqlDbType.DateTime, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, modifiedTime));
            sqlCommand.Parameters.Add(new SqlParameter("@modifiedUserId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, modifiedUserId));
            sqlCommand.Parameters.Add(new SqlParameter("@newsFreeTime", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, newsFreeTime));
            sqlCommand.Parameters.Add(new SqlParameter("@orderTypeCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, orderTypeCode));
            sqlCommand.Parameters.Add(new SqlParameter("@orderedQuantity", SqlDbType.Decimal, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, orderedQuantity));
            sqlCommand.Parameters.Add(new SqlParameter("@priceTypeCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, priceTypeCode));
            sqlCommand.Parameters.Add(new SqlParameter("@receivedTime", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, receivedTime));
            sqlCommand.Parameters.Add(new SqlParameter("@securityId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, securityId));
            sqlCommand.Parameters.Add(new SqlParameter("@settlementId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, settlementId));
            sqlCommand.Parameters.Add(new SqlParameter("@sourceOrderId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, sourceOrderRow[sourceOrderTable.SourceOrderIdColumn]));
            sqlCommand.Parameters.Add(new SqlParameter("@startTime", SqlDbType.DateTime, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, startTime));
            sqlCommand.Parameters.Add(new SqlParameter("@statusCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, statusCode));
            sqlCommand.Parameters.Add(new SqlParameter("@stopPrice", SqlDbType.Decimal, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, stopPrice));
            sqlCommand.Parameters.Add(new SqlParameter("@stopTime", SqlDbType.DateTime, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, stopTime));
            sqlCommand.Parameters.Add(new SqlParameter("@submittedQuantity", SqlDbType.Decimal, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, submittedQuantity));
            sqlCommand.Parameters.Add(new SqlParameter("@submittedTime", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, submittedTime));
            sqlCommand.Parameters.Add(new SqlParameter("@targetPrice", SqlDbType.Decimal, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, targetPrice));
            sqlCommand.Parameters.Add(new SqlParameter("@timeInForceCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, timeInForceCode));
            sqlCommand.Parameters.Add(new SqlParameter("@workingOrderId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, workingOrderId));
            sqlCommand.ExecuteNonQuery();
            // Return Statements
            return sourceOrderRow.SourceOrderId;
        }
        
        /// <summary>Collects the table lock request(s) for an Update operation</summary>
        /// <param name="adoTransaction">A list of locks required for this operation.</param>
        public static void Update(AdoTransaction adoTransaction)
        {
            // These table lock(s) are required for the 'Update' operation.
            adoTransaction.LockRequests.AddWriterLock(ServerMarketData.SourceOrderLock);
        }
        
        /// <summary>Inserts a SourceOrder record using Metadata Parameters.</summary>
        /// <param name="parameters">Contains the metadata parameters.</param>
        public static void Update(ParameterList parameters)
        {
            // Extract the parameters from the command batch.
            AdoTransaction adoTransaction = parameters["adoTransaction"];
            SqlTransaction sqlTransaction = parameters["sqlTransaction"];
            long rowVersion = parameters["rowVersion"];
            object createdTime = parameters["createdTime"].Value;
            object createdUserId = parameters["createdUserId"].Value;
            object destinationId = parameters["destinationId"].Value;
            object externalId0 = parameters["externalId0"].Value;
            object isAdvertised = parameters["isAdvertised"].Value;
            object isAutoExecute = parameters["isAutoExecute"].Value;
            object isCanceled = parameters["isCanceled"].Value;
            object isHeld = parameters["isHeld"].Value;
            object isSteppedIn = parameters["isSteppedIn"].Value;
            object isSubmitted = parameters["isSubmitted"].Value;
            object limitPrice = parameters["limitPrice"].Value;
            object maximumVolatility = parameters["maximumVolatility"].Value;
            object modifiedTime = parameters["modifiedTime"].Value;
            object modifiedUserId = parameters["modifiedUserId"].Value;
            object newsFreeTime = parameters["newsFreeTime"].Value;
            object orderTypeCode = parameters["orderTypeCode"].Value;
            object orderedQuantity = parameters["orderedQuantity"].Value;
            object priceTypeCode = parameters["priceTypeCode"].Value;
            object receivedTime = parameters["receivedTime"].Value;
            object securityId = parameters["securityId"].Value;
            object settlementId = parameters["settlementId"].Value;
            int sourceOrderId = parameters["sourceOrderId"];
            object startTime = parameters["startTime"].Value;
            object statusCode = parameters["statusCode"].Value;
            object stopPrice = parameters["stopPrice"].Value;
            object stopTime = parameters["stopTime"].Value;
            object submittedQuantity = parameters["submittedQuantity"].Value;
            object submittedTime = parameters["submittedTime"].Value;
            object targetPrice = parameters["targetPrice"].Value;
            object timeInForceCode = parameters["timeInForceCode"].Value;
            object workingOrderId = parameters["workingOrderId"].Value;
            // Call the internal method to complete the operation.
            SourceOrder.Update(adoTransaction, sqlTransaction, ref rowVersion, createdTime, createdUserId, destinationId, externalId0, isAdvertised, isAutoExecute, isCanceled, isHeld, isSteppedIn, isSubmitted, limitPrice, maximumVolatility, modifiedTime, modifiedUserId, newsFreeTime, orderTypeCode, orderedQuantity, priceTypeCode, receivedTime, securityId, settlementId, sourceOrderId, startTime, statusCode, stopPrice, stopTime, submittedQuantity, submittedTime, targetPrice, timeInForceCode, workingOrderId);
            // Return values.
            parameters["rowVersion"] = rowVersion;
        }
        
        /// <summary>Updates a SourceOrder record.</summary>
        /// <param name="transaction">Commits or rejects a set of commands as a unit</param>
        /// <param name="rowVersion">The version number of the row</param>
        /// <param name="createdTime">The value for the CreatedTime column.</param>
        /// <param name="createdUserId">The value for the CreatedUserId column.</param>
        /// <param name="destinationId">The value for the DestinationId column.</param>
        /// <param name="externalId0">The value for the ExternalId0 column.</param>
        /// <param name="isAdvertised">The value for the IsAdvertised column.</param>
        /// <param name="isAutoExecute">The value for the IsAutoExecute column.</param>
        /// <param name="isCanceled">The value for the IsCanceled column.</param>
        /// <param name="isHeld">The value for the IsHeld column.</param>
        /// <param name="isSteppedIn">The value for the IsSteppedIn column.</param>
        /// <param name="isSubmitted">The value for the IsSubmitted column.</param>
        /// <param name="limitPrice">The value for the LimitPrice column.</param>
        /// <param name="maximumVolatility">The value for the MaximumVolatility column.</param>
        /// <param name="modifiedTime">The value for the ModifiedTime column.</param>
        /// <param name="modifiedUserId">The value for the ModifiedUserId column.</param>
        /// <param name="newsFreeTime">The value for the NewsFreeTime column.</param>
        /// <param name="orderTypeCode">The value for the OrderTypeCode column.</param>
        /// <param name="orderedQuantity">The value for the OrderedQuantity column.</param>
        /// <param name="priceTypeCode">The value for the PriceTypeCode column.</param>
        /// <param name="receivedTime">The value for the ReceivedTime column.</param>
        /// <param name="securityId">The value for the SecurityId column.</param>
        /// <param name="settlementId">The value for the SettlementId column.</param>
        /// <param name="sourceOrderId">The value for the SourceOrderId column.</param>
        /// <param name="startTime">The value for the StartTime column.</param>
        /// <param name="statusCode">The value for the StatusCode column.</param>
        /// <param name="stopPrice">The value for the StopPrice column.</param>
        /// <param name="stopTime">The value for the StopTime column.</param>
        /// <param name="submittedQuantity">The value for the SubmittedQuantity column.</param>
        /// <param name="submittedTime">The value for the SubmittedTime column.</param>
        /// <param name="targetPrice">The value for the TargetPrice column.</param>
        /// <param name="timeInForceCode">The value for the TimeInForceCode column.</param>
        /// <param name="workingOrderId">The value for the WorkingOrderId column.</param>
        public static void Update(
                    AdoTransaction adoTransaction, 
                    SqlTransaction sqlTransaction, 
                    ref long rowVersion, 
                    object createdTime, 
                    object createdUserId, 
                    object destinationId, 
                    object externalId0, 
                    object isAdvertised, 
                    object isAutoExecute, 
                    object isCanceled, 
                    object isHeld, 
                    object isSteppedIn, 
                    object isSubmitted, 
                    object limitPrice, 
                    object maximumVolatility, 
                    object modifiedTime, 
                    object modifiedUserId, 
                    object newsFreeTime, 
                    object orderTypeCode, 
                    object orderedQuantity, 
                    object priceTypeCode, 
                    object receivedTime, 
                    object securityId, 
                    object settlementId, 
                    int sourceOrderId, 
                    object startTime, 
                    object statusCode, 
                    object stopPrice, 
                    object stopTime, 
                    object submittedQuantity, 
                    object submittedTime, 
                    object targetPrice, 
                    object timeInForceCode, 
                    object workingOrderId)
        {
            // Accessor for the SourceOrder Table.
            ServerMarketData.SourceOrderDataTable sourceOrderTable = ServerMarketData.SourceOrder;
            // Rule #1: Make sure the record exists before updating it.
            ServerMarketData.SourceOrderRow sourceOrderRow = sourceOrderTable.FindBySourceOrderId(sourceOrderId);
            if ((sourceOrderRow == null))
            {
                throw new Exception(string.Format("The SourceOrder table does not have an element identified by {0}", sourceOrderId));
            }
            // Rule #2: Optimistic Concurrency Check
            if ((sourceOrderRow.RowVersion != rowVersion))
            {
                throw new System.Exception("This record is busy.  Please try again later.");
            }
            // Apply Defaults
            if ((createdTime == null))
            {
                createdTime = sourceOrderRow[sourceOrderTable.CreatedTimeColumn];
            }
            if ((createdUserId == null))
            {
                createdUserId = sourceOrderRow[sourceOrderTable.CreatedUserIdColumn];
            }
            if ((destinationId == null))
            {
                destinationId = sourceOrderRow[sourceOrderTable.DestinationIdColumn];
            }
            if ((externalId0 == null))
            {
                externalId0 = sourceOrderRow[sourceOrderTable.ExternalId0Column];
            }
            if ((isAdvertised == null))
            {
                isAdvertised = sourceOrderRow[sourceOrderTable.IsAdvertisedColumn];
            }
            if ((isAutoExecute == null))
            {
                isAutoExecute = sourceOrderRow[sourceOrderTable.IsAutoExecuteColumn];
            }
            if ((isCanceled == null))
            {
                isCanceled = sourceOrderRow[sourceOrderTable.IsCanceledColumn];
            }
            if ((isHeld == null))
            {
                isHeld = sourceOrderRow[sourceOrderTable.IsHeldColumn];
            }
            if ((isSteppedIn == null))
            {
                isSteppedIn = sourceOrderRow[sourceOrderTable.IsSteppedInColumn];
            }
            if ((isSubmitted == null))
            {
                isSubmitted = sourceOrderRow[sourceOrderTable.IsSubmittedColumn];
            }
            if ((limitPrice == null))
            {
                limitPrice = sourceOrderRow[sourceOrderTable.LimitPriceColumn];
            }
            if ((maximumVolatility == null))
            {
                maximumVolatility = sourceOrderRow[sourceOrderTable.MaximumVolatilityColumn];
            }
            if ((modifiedTime == null))
            {
                modifiedTime = sourceOrderRow[sourceOrderTable.ModifiedTimeColumn];
            }
            if ((modifiedUserId == null))
            {
                modifiedUserId = sourceOrderRow[sourceOrderTable.ModifiedUserIdColumn];
            }
            if ((newsFreeTime == null))
            {
                newsFreeTime = sourceOrderRow[sourceOrderTable.NewsFreeTimeColumn];
            }
            if ((orderTypeCode == null))
            {
                orderTypeCode = sourceOrderRow[sourceOrderTable.OrderTypeCodeColumn];
            }
            if ((orderedQuantity == null))
            {
                orderedQuantity = sourceOrderRow[sourceOrderTable.OrderedQuantityColumn];
            }
            if ((priceTypeCode == null))
            {
                priceTypeCode = sourceOrderRow[sourceOrderTable.PriceTypeCodeColumn];
            }
            if ((receivedTime == null))
            {
                receivedTime = sourceOrderRow[sourceOrderTable.ReceivedTimeColumn];
            }
            if ((securityId == null))
            {
                securityId = sourceOrderRow[sourceOrderTable.SecurityIdColumn];
            }
            if ((settlementId == null))
            {
                settlementId = sourceOrderRow[sourceOrderTable.SettlementIdColumn];
            }
            if ((startTime == null))
            {
                startTime = sourceOrderRow[sourceOrderTable.StartTimeColumn];
            }
            if ((statusCode == null))
            {
                statusCode = sourceOrderRow[sourceOrderTable.StatusCodeColumn];
            }
            if ((stopPrice == null))
            {
                stopPrice = sourceOrderRow[sourceOrderTable.StopPriceColumn];
            }
            if ((stopTime == null))
            {
                stopTime = sourceOrderRow[sourceOrderTable.StopTimeColumn];
            }
            if ((submittedQuantity == null))
            {
                submittedQuantity = sourceOrderRow[sourceOrderTable.SubmittedQuantityColumn];
            }
            if ((submittedTime == null))
            {
                submittedTime = sourceOrderRow[sourceOrderTable.SubmittedTimeColumn];
            }
            if ((targetPrice == null))
            {
                targetPrice = sourceOrderRow[sourceOrderTable.TargetPriceColumn];
            }
            if ((timeInForceCode == null))
            {
                timeInForceCode = sourceOrderRow[sourceOrderTable.TimeInForceCodeColumn];
            }
            if ((workingOrderId == null))
            {
                workingOrderId = sourceOrderRow[sourceOrderTable.WorkingOrderIdColumn];
            }
            // Increment the row version
            rowVersion = ServerMarketData.RowVersion.Increment();
            // Update the record in the ADO database.
            sourceOrderRow[sourceOrderTable.RowVersionColumn] = rowVersion;
            sourceOrderRow[sourceOrderTable.CreatedTimeColumn] = createdTime;
            sourceOrderRow[sourceOrderTable.CreatedUserIdColumn] = createdUserId;
            sourceOrderRow[sourceOrderTable.DestinationIdColumn] = destinationId;
            sourceOrderRow[sourceOrderTable.ExternalId0Column] = externalId0;
            sourceOrderRow[sourceOrderTable.IsAdvertisedColumn] = isAdvertised;
            sourceOrderRow[sourceOrderTable.IsAutoExecuteColumn] = isAutoExecute;
            sourceOrderRow[sourceOrderTable.IsCanceledColumn] = isCanceled;
            sourceOrderRow[sourceOrderTable.IsHeldColumn] = isHeld;
            sourceOrderRow[sourceOrderTable.IsSteppedInColumn] = isSteppedIn;
            sourceOrderRow[sourceOrderTable.IsSubmittedColumn] = isSubmitted;
            sourceOrderRow[sourceOrderTable.LimitPriceColumn] = limitPrice;
            sourceOrderRow[sourceOrderTable.MaximumVolatilityColumn] = maximumVolatility;
            sourceOrderRow[sourceOrderTable.ModifiedTimeColumn] = modifiedTime;
            sourceOrderRow[sourceOrderTable.ModifiedUserIdColumn] = modifiedUserId;
            sourceOrderRow[sourceOrderTable.NewsFreeTimeColumn] = newsFreeTime;
            sourceOrderRow[sourceOrderTable.OrderTypeCodeColumn] = orderTypeCode;
            sourceOrderRow[sourceOrderTable.OrderedQuantityColumn] = orderedQuantity;
            sourceOrderRow[sourceOrderTable.PriceTypeCodeColumn] = priceTypeCode;
            sourceOrderRow[sourceOrderTable.ReceivedTimeColumn] = receivedTime;
            sourceOrderRow[sourceOrderTable.SecurityIdColumn] = securityId;
            sourceOrderRow[sourceOrderTable.SettlementIdColumn] = settlementId;
            sourceOrderRow[sourceOrderTable.StartTimeColumn] = startTime;
            sourceOrderRow[sourceOrderTable.StatusCodeColumn] = statusCode;
            sourceOrderRow[sourceOrderTable.StopPriceColumn] = stopPrice;
            sourceOrderRow[sourceOrderTable.StopTimeColumn] = stopTime;
            sourceOrderRow[sourceOrderTable.SubmittedQuantityColumn] = submittedQuantity;
            sourceOrderRow[sourceOrderTable.SubmittedTimeColumn] = submittedTime;
            sourceOrderRow[sourceOrderTable.TargetPriceColumn] = targetPrice;
            sourceOrderRow[sourceOrderTable.TimeInForceCodeColumn] = timeInForceCode;
            sourceOrderRow[sourceOrderTable.WorkingOrderIdColumn] = workingOrderId;
            adoTransaction.DataRows.Add(sourceOrderRow);
            // Update the record in the SQL database.
            SqlCommand sqlCommand = new SqlCommand(@"update ""SourceOrder"" set ""RowVersion""=@rowVersion,""CreatedTime""=@createdTime,""CreatedUserId""=@createdUserId,""DestinationId""=@destinationId,""ExternalId0""=@externalId0,""IsAdvertised""=@isAdvertised,""IsAutoExecute""=@isAutoExecute,""IsCanceled""=@isCanceled,""IsHeld""=@isHeld,""IsSteppedIn""=@isSteppedIn,""IsSubmitted""=@isSubmitted,""LimitPrice""=@limitPrice,""MaximumVolatility""=@maximumVolatility,""ModifiedTime""=@modifiedTime,""ModifiedUserId""=@modifiedUserId,""NewsFreeTime""=@newsFreeTime,""OrderTypeCode""=@orderTypeCode,""OrderedQuantity""=@orderedQuantity,""PriceTypeCode""=@priceTypeCode,""ReceivedTime""=@receivedTime,""SecurityId""=@securityId,""SettlementId""=@settlementId,""StartTime""=@startTime,""StatusCode""=@statusCode,""StopPrice""=@stopPrice,""StopTime""=@stopTime,""SubmittedQuantity""=@submittedQuantity,""SubmittedTime""=@submittedTime,""TargetPrice""=@targetPrice,""TimeInForceCode""=@timeInForceCode,""WorkingOrderId""=@workingOrderId where ""SourceOrderId""=@sourceOrderId");
            sqlCommand.Connection = sqlTransaction.Connection;
            sqlCommand.Transaction = sqlTransaction;
            sqlCommand.Parameters.Add(new SqlParameter("@rowVersion", SqlDbType.BigInt, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, rowVersion));
            sqlCommand.Parameters.Add(new SqlParameter("@createdTime", SqlDbType.DateTime, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, createdTime));
            sqlCommand.Parameters.Add(new SqlParameter("@createdUserId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, createdUserId));
            sqlCommand.Parameters.Add(new SqlParameter("@destinationId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, destinationId));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId0", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId0));
            sqlCommand.Parameters.Add(new SqlParameter("@isAdvertised", SqlDbType.Bit, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, isAdvertised));
            sqlCommand.Parameters.Add(new SqlParameter("@isAutoExecute", SqlDbType.Bit, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, isAutoExecute));
            sqlCommand.Parameters.Add(new SqlParameter("@isCanceled", SqlDbType.Bit, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, isCanceled));
            sqlCommand.Parameters.Add(new SqlParameter("@isHeld", SqlDbType.Bit, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, isHeld));
            sqlCommand.Parameters.Add(new SqlParameter("@isSteppedIn", SqlDbType.Bit, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, isSteppedIn));
            sqlCommand.Parameters.Add(new SqlParameter("@isSubmitted", SqlDbType.Bit, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, isSubmitted));
            sqlCommand.Parameters.Add(new SqlParameter("@limitPrice", SqlDbType.Decimal, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, limitPrice));
            sqlCommand.Parameters.Add(new SqlParameter("@maximumVolatility", SqlDbType.Decimal, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, maximumVolatility));
            sqlCommand.Parameters.Add(new SqlParameter("@modifiedTime", SqlDbType.DateTime, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, modifiedTime));
            sqlCommand.Parameters.Add(new SqlParameter("@modifiedUserId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, modifiedUserId));
            sqlCommand.Parameters.Add(new SqlParameter("@newsFreeTime", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, newsFreeTime));
            sqlCommand.Parameters.Add(new SqlParameter("@orderTypeCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, orderTypeCode));
            sqlCommand.Parameters.Add(new SqlParameter("@orderedQuantity", SqlDbType.Decimal, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, orderedQuantity));
            sqlCommand.Parameters.Add(new SqlParameter("@priceTypeCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, priceTypeCode));
            sqlCommand.Parameters.Add(new SqlParameter("@receivedTime", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, receivedTime));
            sqlCommand.Parameters.Add(new SqlParameter("@securityId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, securityId));
            sqlCommand.Parameters.Add(new SqlParameter("@settlementId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, settlementId));
            sqlCommand.Parameters.Add(new SqlParameter("@sourceOrderId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, sourceOrderId));
            sqlCommand.Parameters.Add(new SqlParameter("@startTime", SqlDbType.DateTime, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, startTime));
            sqlCommand.Parameters.Add(new SqlParameter("@statusCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, statusCode));
            sqlCommand.Parameters.Add(new SqlParameter("@stopPrice", SqlDbType.Decimal, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, stopPrice));
            sqlCommand.Parameters.Add(new SqlParameter("@stopTime", SqlDbType.DateTime, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, stopTime));
            sqlCommand.Parameters.Add(new SqlParameter("@submittedQuantity", SqlDbType.Decimal, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, submittedQuantity));
            sqlCommand.Parameters.Add(new SqlParameter("@submittedTime", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, submittedTime));
            sqlCommand.Parameters.Add(new SqlParameter("@targetPrice", SqlDbType.Decimal, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, targetPrice));
            sqlCommand.Parameters.Add(new SqlParameter("@timeInForceCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, timeInForceCode));
            sqlCommand.Parameters.Add(new SqlParameter("@workingOrderId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, workingOrderId));
            // Update the record in the SQL database.
            sqlCommand.ExecuteNonQuery();
        }
        
        /// <summary>Collects the table lock request(s) for an Update operation</summary>
        /// <param name="adoTransaction">A list of locks required for this operation.</param>
        public static void Delete(AdoTransaction adoTransaction)
        {
            // These table lock(s) are required for the 'Delete' operation.
            adoTransaction.LockRequests.AddWriterLock(ServerMarketData.SourceOrderLock);
        }
        
        /// <summary>Inserts a SourceOrder record using Metadata Parameters.</summary>
        /// <param name="parameters">Contains the metadata parameters.</param>
        public static void Delete(ParameterList parameters)
        {
            // Extract the parameters from the command batch.
            AdoTransaction adoTransaction = parameters["adoTransaction"];
            SqlTransaction sqlTransaction = parameters["sqlTransaction"];
            long rowVersion = parameters["rowVersion"];
            int sourceOrderId = parameters["sourceOrderId"];
            // Call the internal method to complete the operation.
            SourceOrder.Delete(adoTransaction, sqlTransaction, rowVersion, sourceOrderId);
        }
        
        /// <summary>Deletes a SourceOrder record.</summary>
        /// <param name="transaction">Commits or rejects a set of commands as a unit</param>
        /// <param name="RowVersion">The version number of this row.</param>
        /// <param name="sourceOrderId">The value for the SourceOrderId column.</param>
        /// <param name="archive">true to archive the object, false to unarchive it.</param>
        public static void Delete(AdoTransaction adoTransaction, SqlTransaction sqlTransaction, long rowVersion, int sourceOrderId)
        {
            // Accessor for the SourceOrder Table.
            ServerMarketData.SourceOrderDataTable sourceOrderTable = ServerMarketData.SourceOrder;
            // Rule #1: Make sure the record exists before updating it.
            ServerMarketData.SourceOrderRow sourceOrderRow = sourceOrderTable.FindBySourceOrderId(sourceOrderId);
            if ((sourceOrderRow == null))
            {
                throw new Exception(string.Format("The SourceOrder table does not have an element identified by {0}", sourceOrderId));
            }
            // Rule #2: Optimistic Concurrency Check
            if ((sourceOrderRow.RowVersion != rowVersion))
            {
                throw new System.Exception("This record is busy.  Please try again later.");
            }
            // Delete the child records.
            // Increment the row version
            rowVersion = ServerMarketData.RowVersion.Increment();
            // Delete the record in the ADO database.
            sourceOrderRow[sourceOrderTable.RowVersionColumn] = rowVersion;
            adoTransaction.DataRows.Add(sourceOrderRow);
            sourceOrderRow.Delete();
            // Delete the record in the SQL database.
            SqlCommand sqlCommand = new SqlCommand("update \"SourceOrder\" set \"IsDeleted\" = 1 where \"SourceOrderId\"=@sourceOrderId");
            sqlCommand.Connection = sqlTransaction.Connection;
            sqlCommand.Transaction = sqlTransaction;
            sqlCommand.Parameters.Add(new SqlParameter("@sourceOrderId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, sourceOrderId));
            sqlCommand.ExecuteNonQuery();
        }
        
        /// <summary>Collects the table lock request(s) for an Update operation</summary>
        /// <param name="adoTransaction">A list of locks required for this operation.</param>
        public static void Archive(AdoTransaction adoTransaction)
        {
            // These table lock(s) are required for the 'Archive' operation.
            adoTransaction.LockRequests.AddWriterLock(ServerMarketData.SourceOrderLock);
        }
        
        /// <summary>Inserts a SourceOrder record using Metadata Parameters.</summary>
        /// <param name="parameters">Contains the metadata parameters.</param>
        public static void Archive(ParameterList parameters)
        {
            // Extract the parameters from the command batch.
            AdoTransaction adoTransaction = parameters["adoTransaction"];
            SqlTransaction sqlTransaction = parameters["sqlTransaction"];
            long rowVersion = parameters["rowVersion"];
            int sourceOrderId = parameters["sourceOrderId"];
            // Call the internal method to complete the operation.
            SourceOrder.Archive(adoTransaction, sqlTransaction, rowVersion, sourceOrderId);
        }
        
        /// <summary>Archives a SourceOrder record.</summary>
        /// <param name="transaction">Commits or rejects a set of commands as a unit</param>
        /// <param name="RowVersion">The version number of this row.</param>
        /// <param name="sourceOrderId">The value for the SourceOrderId column.</param>
        /// <param name="archive">true to archive the object, false to unarchive it.</param>
        public static void Archive(AdoTransaction adoTransaction, SqlTransaction sqlTransaction, long rowVersion, int sourceOrderId)
        {
            // Accessor for the SourceOrder Table.
            ServerMarketData.SourceOrderDataTable sourceOrderTable = ServerMarketData.SourceOrder;
            // Rule #1: Make sure the record exists before updating it.
            ServerMarketData.SourceOrderRow sourceOrderRow = sourceOrderTable.FindBySourceOrderId(sourceOrderId);
            if ((sourceOrderRow == null))
            {
                throw new Exception(string.Format("The SourceOrder table does not have an element identified by {0}", sourceOrderId));
            }
            // Rule #2: Optimistic Concurrency Check
            if ((sourceOrderRow.RowVersion != rowVersion))
            {
                throw new System.Exception("This record is busy.  Please try again later.");
            }
            // Archive the child records.
            // Increment the row version
            rowVersion = ServerMarketData.RowVersion.Increment();
            // Delete the record in the ADO database.
            sourceOrderRow[sourceOrderTable.RowVersionColumn] = rowVersion;
            adoTransaction.DataRows.Add(sourceOrderRow);
            sourceOrderRow.Delete();
            // Archive the record in the SQL database.
            SqlCommand sqlCommand = new SqlCommand("update \"SourceOrder\" set \"IsArchived\" = 1 where \"SourceOrderId\"=@sourceOrderId");
            sqlCommand.Connection = sqlTransaction.Connection;
            sqlCommand.Transaction = sqlTransaction;
            sqlCommand.Parameters.Add(new SqlParameter("@sourceOrderId", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, sourceOrderId));
            sqlCommand.ExecuteNonQuery();
        }
    }
}
