echo "AxDBCCTRLLib.dll:"
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Real Time Pricing\bin\Debug\AxDBCCTRLLib.dll"
echo "Batch:" 
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Batch\bin\Debug\Batch.dll"
echo "Configuration Sections:" 
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Configuration Sections\bin\Debug\Configuration Sections.dll"
echo "Core Service:" 
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Core Service\bin\Debug\Core Service.dll"
echo "DBCCTRLLib.dll:"
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Real Time Pricing\bin\Debug\DBCCTRLLib.dll"
echo "External Service:" 
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\External Service\bin\Debug\External Service.dll"
echo "Guardian Library:" 
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Guardian Library\bin\Debug\Guardian Library.dll"
echo "Mark Three Library:" 
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Mark Three Library\bin\Debug\Mark Three Library.dll"
echo "Market Data:" 
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Market Data\bin\Debug\Market Data.dll"
echo "Matching Service:" 
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Matching Service\bin\Debug\Matching Service.dll"
echo "Price Simulator:" 
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Price Simulator\bin\Debug\Price Simulator.dll"
echo "Real Time Pricing"
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Real Time Pricing\bin\Debug\Real Time Pricing.dll"
echo "Server Market Data:" 
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Server Market Data\bin\Debug\Server Market Data.dll"
echo "Trading Service:" 
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Guardian\Trading Service\bin\Debug\Trading Service.dll"
echo "Web Transaction:" 
sn -q -Vr "C:\My Documents\Visual Studio 2005\Projects\Mark Three Software\Web Transaction\bin\Debug\Web Transaction.dll"
