@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Advertisement Viewer/obj/Release/Advertisement Viewer.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Batch/obj/Release/Batch.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Blotter Viewer/obj/Release/Blotter Viewer.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Blotter Detail Viewer/obj/Release/Blotter Detail Viewer.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Browser Viewer/obj/Release/Browser Viewer.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Chart Viewer/obj/Release/AxInterop.OWC11.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Chart Viewer/obj/Release/Chart Viewer.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Chart Viewer/obj/Release/Interop.OWC11.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Client Library/obj/Release/Client Library.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Client Market Data/obj/Release/Client Market Data.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Configuration Sections/obj/Release/Configuration Sections.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Destination Order Viewer/obj/Release/Destination Order Viewer.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Order Form/obj/Release/Order Form.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Folder List/obj/Release/Folder List.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Execution Viewer/obj/Release/Execution Viewer.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Guardian Forms/obj/Release/Guardian Forms.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Guardian Library/obj/Release/Guardian Library.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Mark Three Forms/obj/Release/Mark Three Forms.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Mark Three Library/obj/Release/Mark Three Library.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Market Data/obj/Release/Market Data.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Match Viewer/obj/Release/Match Viewer.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Match History Viewer/obj/Release/Match History Viewer.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Negotiation Console/obj/Release/Negotiation Console.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Negotiation Service/obj/Release/Negotiation Service.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Object Library/obj/Release/Object Library.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Options/obj/Release/Options.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Order Book Viewer/obj/Release/Order Book Viewer.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/QuoteViewer/obj/Release/QuoteViewer.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Source Order Viewer/obj/Release/Source Order Viewer.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Spreadsheet Viewer/obj/Release/Spreadsheet Viewer.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/TOMS Scraper/obj/Release/TOMS Scraper.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/User Preferences/obj/Release/User Preferences.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Web Transaction Protocol/obj/Release/Web Transaction Protocol.dll" "C:/Cryptography/Mark Three Software/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Working Order Viewer/obj/Release/Working Order Viewer.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
@sn -q -R "C:/My Documents/Visual Studio 2005/Projects/Mark Three Software/Guardian/Volume Chart Viewer/obj/Release/Volume Chart Viewer.dll" "C:/Cryptography/Mark Three Software/Guardian/Key Pair.snk"
