CREATE LOGIN [ARIEL\ASPNET] FROM WINDOWS;
CREATE LOGIN [ARIEL\Carol Hill] FROM WINDOWS;
CREATE LOGIN [ARIEL\Charles Rodriguez] FROM WINDOWS;
CREATE LOGIN [ARIEL\Elaine Russo] FROM WINDOWS;
CREATE LOGIN [ARIEL\Gary Brown] FROM WINDOWS;
CREATE LOGIN [ARIEL\Gilbert Horowitz] FROM WINDOWS;
CREATE LOGIN [ARIEL\Guardian Admin] FROM WINDOWS;
CREATE LOGIN [ARIEL\Guardian Operator] FROM WINDOWS;
CREATE LOGIN [ARIEL\Kareem Rao] FROM WINDOWS;
CREATE LOGIN [ARIEL\Kate Schwartz] FROM WINDOWS;
CREATE LOGIN [ARIEL\Manny Cortez] FROM WINDOWS;
CREATE LOGIN [ARIEL\Roberto Garcia] FROM WINDOWS;
CREATE LOGIN [ARIEL\Russell Jackson] FROM WINDOWS;
CREATE LOGIN [ARIEL\Susan Chung] FROM WINDOWS;
CREATE LOGIN [ARIEL\Tony De Silva] FROM WINDOWS;
CREATE LOGIN [ARIEL\Victor Margolin] FROM WINDOWS;
CREATE LOGIN [ARIEL\Yoshio Shimura] FROM WINDOWS;
go


