//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkThree.Quasar.Core
{
    using MarkThree.Quasar;
    using MarkThree.Quasar.Server;
    using MarkThree;
    using System;
    using System.Collections;
    using System.Data;
    using System.Data.SqlClient;
    
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    public class HolidayType
    {
        
        /// This value is used to map the object to a persistent storage device.  The parameters for the storage
        /// are found in the configuration file for this service.
        public static string PersistentStore = "Quasar";
        
        /// This member provides access to the in-memory database.
        private static ServerDataModel serverDataModel = new ServerDataModel();
        
        /// <summary>Collects the table lock request(s) for an Insert operation</summary>
        /// <param name="adoTransaction">A list of locks required for this operation.</param>
        public static void Insert(AdoTransaction adoTransaction)
        {
            // These table lock(s) are required for this operation.
            adoTransaction.LockRequests.Add(new TableWriterRequest(ServerDataModel.HolidayType));
        }
        
        /// <summary>Inserts a HolidayType record using Metadata Parameters.</summary>
        /// <param name="parameters">Contains the metadata parameters.</param>
        public static void Insert(ParameterList parameters)
        {
            // Extract the parameters from the command batch.
            AdoTransaction adoTransaction = parameters["adoTransaction"];
            SqlTransaction sqlTransaction = parameters["sqlTransaction"];
            int holidayTypeCode = parameters["holidayTypeCode"];
            string description = parameters["description"];
            object externalId0 = parameters["externalId0"].Value;
            object externalId1 = parameters["externalId1"].Value;
            object externalId2 = parameters["externalId2"].Value;
            object externalId3 = parameters["externalId3"].Value;
            // The rowVersion is passed back to the caller in the event it's needed for additional commands in the batch.
            long rowVersion = long.MinValue;
            // Call the internal method to complete the operation.
            HolidayType.Insert(adoTransaction, sqlTransaction, ref rowVersion, holidayTypeCode, description, externalId0, externalId1, externalId2, externalId3);
            // Return values.
            parameters["rowVersion"] = rowVersion;
        }
        
        /// <summary>Inserts a HolidayType record.</summary>
        /// <param name="transaction">Commits or rejects a set of commands as a unit</param>
        /// <param name="holidayTypeCode">The value for the HolidayTypeCode column.</param>
        /// <param name="description">The value for the Description column.</param>
        /// <param name="externalId0">The value for the ExternalId0 column.</param>
        /// <param name="externalId1">The value for the ExternalId1 column.</param>
        /// <param name="externalId2">The value for the ExternalId2 column.</param>
        /// <param name="externalId3">The value for the ExternalId3 column.</param>
        public static void Insert(AdoTransaction adoTransaction, SqlTransaction sqlTransaction, ref long rowVersion, int holidayTypeCode, string description, object externalId0, object externalId1, object externalId2, object externalId3)
        {
            // Accessor for the HolidayType Table.
            ServerDataModel.HolidayTypeDataTable holidayTypeTable = ServerDataModel.HolidayType;
            // Apply Defaults
            if ((externalId0 == null))
            {
                externalId0 = System.DBNull.Value;
            }
            if ((externalId1 == null))
            {
                externalId1 = System.DBNull.Value;
            }
            if ((externalId2 == null))
            {
                externalId2 = System.DBNull.Value;
            }
            if ((externalId3 == null))
            {
                externalId3 = System.DBNull.Value;
            }
            // Increment the row version
            rowVersion = ServerDataModel.RowVersion.Increment();
            // Insert the record into the ADO database.
            ServerDataModel.HolidayTypeRow holidayTypeRow = holidayTypeTable.NewHolidayTypeRow();
            holidayTypeRow[holidayTypeTable.RowVersionColumn] = rowVersion;
            holidayTypeRow[holidayTypeTable.HolidayTypeCodeColumn] = holidayTypeCode;
            holidayTypeRow[holidayTypeTable.DescriptionColumn] = description;
            holidayTypeRow[holidayTypeTable.ExternalId0Column] = externalId0;
            holidayTypeRow[holidayTypeTable.ExternalId1Column] = externalId1;
            holidayTypeRow[holidayTypeTable.ExternalId2Column] = externalId2;
            holidayTypeRow[holidayTypeTable.ExternalId3Column] = externalId3;
            holidayTypeTable.AddHolidayTypeRow(holidayTypeRow);
            adoTransaction.DataRows.Add(holidayTypeRow);
            // Insert the record into the SQL database.
            SqlCommand sqlCommand = new SqlCommand("insert \"HolidayType\" (\"rowVersion\",\"HolidayTypeCode\",\"Description\",\"ExternalId0\"," +
                    "\"ExternalId1\",\"ExternalId2\",\"ExternalId3\") values (@rowVersion,@holidayTypeCode," +
                    "@description,@externalId0,@externalId1,@externalId2,@externalId3)");
            sqlCommand.Connection = sqlTransaction.Connection;
            sqlCommand.Transaction = sqlTransaction;
            sqlCommand.Parameters.Add(new SqlParameter("@rowVersion", SqlDbType.BigInt, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, rowVersion));
            sqlCommand.Parameters.Add(new SqlParameter("@holidayTypeCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, holidayTypeCode));
            sqlCommand.Parameters.Add(new SqlParameter("@description", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, description));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId0", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId0));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId1", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId1));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId2", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId2));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId3", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId3));
            sqlCommand.ExecuteNonQuery();
        }
        
        /// <summary>Collects the table lock request(s) for an Update operation</summary>
        /// <param name="adoTransaction">A list of locks required for this operation.</param>
        public static void Update(AdoTransaction adoTransaction)
        {
            // These table lock(s) are required for the 'Update' operation.
            adoTransaction.LockRequests.Add(new TableWriterRequest(ServerDataModel.HolidayType));
            Holiday.Update(adoTransaction);
        }
        
        /// <summary>Inserts a HolidayType record using Metadata Parameters.</summary>
        /// <param name="parameters">Contains the metadata parameters.</param>
        public static void Update(ParameterList parameters)
        {
            // Extract the parameters from the command batch.
            AdoTransaction adoTransaction = parameters["adoTransaction"];
            SqlTransaction sqlTransaction = parameters["sqlTransaction"];
            long rowVersion = parameters["rowVersion"];
            int holidayTypeCode = parameters["holidayTypeCode"];
            object description = parameters["description"].Value;
            object externalId0 = parameters["externalId0"].Value;
            object externalId1 = parameters["externalId1"].Value;
            object externalId2 = parameters["externalId2"].Value;
            object externalId3 = parameters["externalId3"].Value;
            // Call the internal method to complete the operation.
            HolidayType.Update(adoTransaction, sqlTransaction, ref rowVersion, holidayTypeCode, description, externalId0, externalId1, externalId2, externalId3);
            // Return values.
            parameters["rowVersion"] = rowVersion;
        }
        
        /// <summary>Updates a HolidayType record.</summary>
        /// <param name="transaction">Commits or rejects a set of commands as a unit</param>
        /// <param name="rowVersion">The version number of the row</param>
        /// <param name="holidayTypeCode">The value for the HolidayTypeCode column.</param>
        /// <param name="description">The value for the Description column.</param>
        /// <param name="externalId0">The value for the ExternalId0 column.</param>
        /// <param name="externalId1">The value for the ExternalId1 column.</param>
        /// <param name="externalId2">The value for the ExternalId2 column.</param>
        /// <param name="externalId3">The value for the ExternalId3 column.</param>
        public static void Update(AdoTransaction adoTransaction, SqlTransaction sqlTransaction, ref long rowVersion, int holidayTypeCode, object description, object externalId0, object externalId1, object externalId2, object externalId3)
        {
            // Accessor for the HolidayType Table.
            ServerDataModel.HolidayTypeDataTable holidayTypeTable = ServerDataModel.HolidayType;
            // Rule #1: Make sure the record exists before updating it.
            ServerDataModel.HolidayTypeRow holidayTypeRow = holidayTypeTable.FindByHolidayTypeCode(holidayTypeCode);
            if ((holidayTypeRow == null))
            {
                throw new Exception(string.Format("The HolidayType table does not have an element identified by {0}", holidayTypeCode));
            }
            // Rule #2: Optimistic Concurrency Check
            if ((holidayTypeRow.RowVersion != rowVersion))
            {
                throw new System.Exception("This record is busy.  Please try again later.");
            }
            // Apply Defaults
            if ((description == null))
            {
                description = holidayTypeRow[holidayTypeTable.DescriptionColumn];
            }
            if ((externalId0 == null))
            {
                externalId0 = holidayTypeRow[holidayTypeTable.ExternalId0Column];
            }
            if ((externalId1 == null))
            {
                externalId1 = holidayTypeRow[holidayTypeTable.ExternalId1Column];
            }
            if ((externalId2 == null))
            {
                externalId2 = holidayTypeRow[holidayTypeTable.ExternalId2Column];
            }
            if ((externalId3 == null))
            {
                externalId3 = holidayTypeRow[holidayTypeTable.ExternalId3Column];
            }
            // Increment the row version
            rowVersion = ServerDataModel.RowVersion.Increment();
            // Update the record in the ADO database.
            holidayTypeRow[holidayTypeTable.RowVersionColumn] = rowVersion;
            holidayTypeRow[holidayTypeTable.DescriptionColumn] = description;
            holidayTypeRow[holidayTypeTable.ExternalId0Column] = externalId0;
            holidayTypeRow[holidayTypeTable.ExternalId1Column] = externalId1;
            holidayTypeRow[holidayTypeTable.ExternalId2Column] = externalId2;
            holidayTypeRow[holidayTypeTable.ExternalId3Column] = externalId3;
            adoTransaction.DataRows.Add(holidayTypeRow);
            // Update the record in the SQL database.
            SqlCommand sqlCommand = new SqlCommand("update \"HolidayType\" set \"RowVersion\"=@rowVersion,\"Description\"=@description,\"Ext" +
                    "ernalId0\"=@externalId0,\"ExternalId1\"=@externalId1,\"ExternalId2\"=@externalId2,\"Ex" +
                    "ternalId3\"=@externalId3 where \"HolidayTypeCode\"=@holidayTypeCode");
            sqlCommand.Connection = sqlTransaction.Connection;
            sqlCommand.Transaction = sqlTransaction;
            sqlCommand.Parameters.Add(new SqlParameter("@rowVersion", SqlDbType.BigInt, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, rowVersion));
            sqlCommand.Parameters.Add(new SqlParameter("@holidayTypeCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, holidayTypeCode));
            sqlCommand.Parameters.Add(new SqlParameter("@description", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, description));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId0", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId0));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId1", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId1));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId2", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId2));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId3", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId3));
            // Update the record in the SQL database.
            sqlCommand.ExecuteNonQuery();
        }
        
        /// <summary>Collects the table lock request(s) for an Update operation</summary>
        /// <param name="adoTransaction">A list of locks required for this operation.</param>
        public static void Delete(AdoTransaction adoTransaction)
        {
            // These table lock(s) are required for the 'Delete' operation.
            adoTransaction.LockRequests.Add(new TableWriterRequest(ServerDataModel.HolidayType));
            Holiday.Archive(adoTransaction);
        }
        
        /// <summary>Inserts a HolidayType record using Metadata Parameters.</summary>
        /// <param name="parameters">Contains the metadata parameters.</param>
        public static void Delete(ParameterList parameters)
        {
            // Extract the parameters from the command batch.
            AdoTransaction adoTransaction = parameters["adoTransaction"];
            SqlTransaction sqlTransaction = parameters["sqlTransaction"];
            long rowVersion = parameters["rowVersion"];
            int holidayTypeCode = parameters["holidayTypeCode"];
            // Call the internal method to complete the operation.
            HolidayType.Delete(adoTransaction, sqlTransaction, rowVersion, holidayTypeCode);
        }
        
        /// <summary>Deletes a HolidayType record.</summary>
        /// <param name="transaction">Commits or rejects a set of commands as a unit</param>
        /// <param name="RowVersion">The version number of this row.</param>
        /// <param name="holidayTypeCode">The value for the HolidayTypeCode column.</param>
        /// <param name="archive">true to archive the object, false to unarchive it.</param>
        public static void Delete(AdoTransaction adoTransaction, SqlTransaction sqlTransaction, long rowVersion, int holidayTypeCode)
        {
            // Accessor for the HolidayType Table.
            ServerDataModel.HolidayTypeDataTable holidayTypeTable = ServerDataModel.HolidayType;
            // Rule #1: Make sure the record exists before updating it.
            ServerDataModel.HolidayTypeRow holidayTypeRow = holidayTypeTable.FindByHolidayTypeCode(holidayTypeCode);
            if ((holidayTypeRow == null))
            {
                throw new Exception(string.Format("The HolidayType table does not have an element identified by {0}", holidayTypeCode));
            }
            // Rule #2: Optimistic Concurrency Check
            if ((holidayTypeRow.RowVersion != rowVersion))
            {
                throw new System.Exception("This record is busy.  Please try again later.");
            }
            // Delete the child records.
            for (int index = 0; (index < holidayTypeRow.GetHolidayRows().Length); index = (index + 1))
            {
                ServerDataModel.HolidayRow childHolidayRow = holidayTypeRow.GetHolidayRows()[index];
                Holiday.Delete(adoTransaction, sqlTransaction, childHolidayRow.RowVersion, childHolidayRow.HolidayId);
            }
            // Increment the row version
            rowVersion = ServerDataModel.RowVersion.Increment();
            // Delete the record in the ADO database.
            holidayTypeRow[holidayTypeTable.RowVersionColumn] = rowVersion;
            adoTransaction.DataRows.Add(holidayTypeRow);
            holidayTypeRow.Delete();
            // Delete the record in the SQL database.
            SqlCommand sqlCommand = new SqlCommand("update \"HolidayType\" set \"IsDeleted\" = 1 where \"HolidayTypeCode\"=@holidayTypeCode" +
                    "");
            sqlCommand.Connection = sqlTransaction.Connection;
            sqlCommand.Transaction = sqlTransaction;
            sqlCommand.Parameters.Add(new SqlParameter("@holidayTypeCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, holidayTypeCode));
            sqlCommand.ExecuteNonQuery();
        }
        
        /// <summary>Collects the table lock request(s) for an Update operation</summary>
        /// <param name="adoTransaction">A list of locks required for this operation.</param>
        public static void Archive(AdoTransaction adoTransaction)
        {
            // These table lock(s) are required for the 'Archive' operation.
            adoTransaction.LockRequests.Add(new TableWriterRequest(ServerDataModel.HolidayType));
            Holiday.Archive(adoTransaction);
        }
        
        /// <summary>Inserts a HolidayType record using Metadata Parameters.</summary>
        /// <param name="parameters">Contains the metadata parameters.</param>
        public static void Archive(ParameterList parameters)
        {
            // Extract the parameters from the command batch.
            AdoTransaction adoTransaction = parameters["adoTransaction"];
            SqlTransaction sqlTransaction = parameters["sqlTransaction"];
            long rowVersion = parameters["rowVersion"];
            int holidayTypeCode = parameters["holidayTypeCode"];
            // Call the internal method to complete the operation.
            HolidayType.Archive(adoTransaction, sqlTransaction, rowVersion, holidayTypeCode);
        }
        
        /// <summary>Archives a HolidayType record.</summary>
        /// <param name="transaction">Commits or rejects a set of commands as a unit</param>
        /// <param name="RowVersion">The version number of this row.</param>
        /// <param name="holidayTypeCode">The value for the HolidayTypeCode column.</param>
        /// <param name="archive">true to archive the object, false to unarchive it.</param>
        public static void Archive(AdoTransaction adoTransaction, SqlTransaction sqlTransaction, long rowVersion, int holidayTypeCode)
        {
            // Accessor for the HolidayType Table.
            ServerDataModel.HolidayTypeDataTable holidayTypeTable = ServerDataModel.HolidayType;
            // Rule #1: Make sure the record exists before updating it.
            ServerDataModel.HolidayTypeRow holidayTypeRow = holidayTypeTable.FindByHolidayTypeCode(holidayTypeCode);
            if ((holidayTypeRow == null))
            {
                throw new Exception(string.Format("The HolidayType table does not have an element identified by {0}", holidayTypeCode));
            }
            // Rule #2: Optimistic Concurrency Check
            if ((holidayTypeRow.RowVersion != rowVersion))
            {
                throw new System.Exception("This record is busy.  Please try again later.");
            }
            // Archive the child records.
            for (int index = 0; (index < holidayTypeRow.GetHolidayRows().Length); index = (index + 1))
            {
                ServerDataModel.HolidayRow childHolidayRow = holidayTypeRow.GetHolidayRows()[index];
                Holiday.Archive(adoTransaction, sqlTransaction, childHolidayRow.RowVersion, childHolidayRow.HolidayId);
            }
            // Increment the row version
            rowVersion = ServerDataModel.RowVersion.Increment();
            // Delete the record in the ADO database.
            holidayTypeRow[holidayTypeTable.RowVersionColumn] = rowVersion;
            adoTransaction.DataRows.Add(holidayTypeRow);
            holidayTypeRow.Delete();
            // Archive the record in the SQL database.
            SqlCommand sqlCommand = new SqlCommand("update \"HolidayType\" set \"IsArchived\" = 1 where \"HolidayTypeCode\"=@holidayTypeCod" +
                    "e");
            sqlCommand.Connection = sqlTransaction.Connection;
            sqlCommand.Transaction = sqlTransaction;
            sqlCommand.Parameters.Add(new SqlParameter("@holidayTypeCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, holidayTypeCode));
            sqlCommand.ExecuteNonQuery();
        }
    }
}
