//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkThree.Quasar.Core
{
    using MarkThree.Quasar;
    using MarkThree.Quasar.Server;
    using MarkThree;
    using System;
    using System.Collections;
    using System.Data;
    using System.Data.SqlClient;
    
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    public class ModelType
    {
        
        /// This value is used to map the object to a persistent storage device.  The parameters for the storage
        /// are found in the configuration file for this service.
        public static string PersistentStore = "Quasar";
        
        /// This member provides access to the in-memory database.
        private static ServerDataModel serverDataModel = new ServerDataModel();
        
        /// <summary>Collects the table lock request(s) for an Insert operation</summary>
        /// <param name="adoTransaction">A list of locks required for this operation.</param>
        public static void Insert(AdoTransaction adoTransaction)
        {
            // These table lock(s) are required for this operation.
            adoTransaction.LockRequests.Add(new TableWriterRequest(ServerDataModel.ModelType));
        }
        
        /// <summary>Inserts a ModelType record using Metadata Parameters.</summary>
        /// <param name="parameters">Contains the metadata parameters.</param>
        public static void Insert(ParameterList parameters)
        {
            // Extract the parameters from the command batch.
            AdoTransaction adoTransaction = parameters["adoTransaction"];
            SqlTransaction sqlTransaction = parameters["sqlTransaction"];
            int modelTypeCode = parameters["modelTypeCode"];
            string description = parameters["description"];
            object externalId0 = parameters["externalId0"].Value;
            object externalId1 = parameters["externalId1"].Value;
            // The rowVersion is passed back to the caller in the event it's needed for additional commands in the batch.
            long rowVersion = long.MinValue;
            // Call the internal method to complete the operation.
            ModelType.Insert(adoTransaction, sqlTransaction, ref rowVersion, modelTypeCode, description, externalId0, externalId1);
            // Return values.
            parameters["rowVersion"] = rowVersion;
        }
        
        /// <summary>Inserts a ModelType record.</summary>
        /// <param name="transaction">Commits or rejects a set of commands as a unit</param>
        /// <param name="modelTypeCode">The value for the ModelTypeCode column.</param>
        /// <param name="description">The value for the Description column.</param>
        /// <param name="externalId0">The value for the ExternalId0 column.</param>
        /// <param name="externalId1">The value for the ExternalId1 column.</param>
        public static void Insert(AdoTransaction adoTransaction, SqlTransaction sqlTransaction, ref long rowVersion, int modelTypeCode, string description, object externalId0, object externalId1)
        {
            // Accessor for the ModelType Table.
            ServerDataModel.ModelTypeDataTable modelTypeTable = ServerDataModel.ModelType;
            // Apply Defaults
            if ((externalId0 == null))
            {
                externalId0 = System.DBNull.Value;
            }
            if ((externalId1 == null))
            {
                externalId1 = System.DBNull.Value;
            }
            // Increment the row version
            rowVersion = ServerDataModel.RowVersion.Increment();
            // Insert the record into the ADO database.
            ServerDataModel.ModelTypeRow modelTypeRow = modelTypeTable.NewModelTypeRow();
            modelTypeRow[modelTypeTable.RowVersionColumn] = rowVersion;
            modelTypeRow[modelTypeTable.ModelTypeCodeColumn] = modelTypeCode;
            modelTypeRow[modelTypeTable.DescriptionColumn] = description;
            modelTypeRow[modelTypeTable.ExternalId0Column] = externalId0;
            modelTypeRow[modelTypeTable.ExternalId1Column] = externalId1;
            modelTypeTable.AddModelTypeRow(modelTypeRow);
            adoTransaction.DataRows.Add(modelTypeRow);
            // Insert the record into the SQL database.
            SqlCommand sqlCommand = new SqlCommand("insert \"ModelType\" (\"rowVersion\",\"ModelTypeCode\",\"Description\",\"ExternalId0\",\"Ext" +
                    "ernalId1\") values (@rowVersion,@modelTypeCode,@description,@externalId0,@externa" +
                    "lId1)");
            sqlCommand.Connection = sqlTransaction.Connection;
            sqlCommand.Transaction = sqlTransaction;
            sqlCommand.Parameters.Add(new SqlParameter("@rowVersion", SqlDbType.BigInt, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, rowVersion));
            sqlCommand.Parameters.Add(new SqlParameter("@modelTypeCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, modelTypeCode));
            sqlCommand.Parameters.Add(new SqlParameter("@description", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, description));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId0", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId0));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId1", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId1));
            sqlCommand.ExecuteNonQuery();
        }
        
        /// <summary>Collects the table lock request(s) for an Update operation</summary>
        /// <param name="adoTransaction">A list of locks required for this operation.</param>
        public static void Update(AdoTransaction adoTransaction)
        {
            // These table lock(s) are required for the 'Update' operation.
            adoTransaction.LockRequests.Add(new TableWriterRequest(ServerDataModel.ModelType));
            Model.UpdateChildren(adoTransaction);
        }
        
        /// <summary>Inserts a ModelType record using Metadata Parameters.</summary>
        /// <param name="parameters">Contains the metadata parameters.</param>
        public static void Update(ParameterList parameters)
        {
            // Extract the parameters from the command batch.
            AdoTransaction adoTransaction = parameters["adoTransaction"];
            SqlTransaction sqlTransaction = parameters["sqlTransaction"];
            long rowVersion = parameters["rowVersion"];
            int modelTypeCode = parameters["modelTypeCode"];
            object description = parameters["description"].Value;
            object externalId0 = parameters["externalId0"].Value;
            object externalId1 = parameters["externalId1"].Value;
            // Call the internal method to complete the operation.
            ModelType.Update(adoTransaction, sqlTransaction, ref rowVersion, modelTypeCode, description, externalId0, externalId1);
            // Return values.
            parameters["rowVersion"] = rowVersion;
        }
        
        /// <summary>Updates a ModelType record.</summary>
        /// <param name="transaction">Commits or rejects a set of commands as a unit</param>
        /// <param name="rowVersion">The version number of the row</param>
        /// <param name="modelTypeCode">The value for the ModelTypeCode column.</param>
        /// <param name="description">The value for the Description column.</param>
        /// <param name="externalId0">The value for the ExternalId0 column.</param>
        /// <param name="externalId1">The value for the ExternalId1 column.</param>
        public static void Update(AdoTransaction adoTransaction, SqlTransaction sqlTransaction, ref long rowVersion, int modelTypeCode, object description, object externalId0, object externalId1)
        {
            // Accessor for the ModelType Table.
            ServerDataModel.ModelTypeDataTable modelTypeTable = ServerDataModel.ModelType;
            // Rule #1: Make sure the record exists before updating it.
            ServerDataModel.ModelTypeRow modelTypeRow = modelTypeTable.FindByModelTypeCode(modelTypeCode);
            if ((modelTypeRow == null))
            {
                throw new Exception(string.Format("The ModelType table does not have an element identified by {0}", modelTypeCode));
            }
            // Rule #2: Optimistic Concurrency Check
            if ((modelTypeRow.RowVersion != rowVersion))
            {
                throw new System.Exception("This record is busy.  Please try again later.");
            }
            // Apply Defaults
            if ((description == null))
            {
                description = modelTypeRow[modelTypeTable.DescriptionColumn];
            }
            if ((externalId0 == null))
            {
                externalId0 = modelTypeRow[modelTypeTable.ExternalId0Column];
            }
            if ((externalId1 == null))
            {
                externalId1 = modelTypeRow[modelTypeTable.ExternalId1Column];
            }
            // Increment the row version
            rowVersion = ServerDataModel.RowVersion.Increment();
            // Update the record in the ADO database.
            modelTypeRow[modelTypeTable.RowVersionColumn] = rowVersion;
            modelTypeRow[modelTypeTable.DescriptionColumn] = description;
            modelTypeRow[modelTypeTable.ExternalId0Column] = externalId0;
            modelTypeRow[modelTypeTable.ExternalId1Column] = externalId1;
            adoTransaction.DataRows.Add(modelTypeRow);
            // Update the record in the SQL database.
            SqlCommand sqlCommand = new SqlCommand("update \"ModelType\" set \"RowVersion\"=@rowVersion,\"Description\"=@description,\"Exter" +
                    "nalId0\"=@externalId0,\"ExternalId1\"=@externalId1 where \"ModelTypeCode\"=@modelType" +
                    "Code");
            sqlCommand.Connection = sqlTransaction.Connection;
            sqlCommand.Transaction = sqlTransaction;
            sqlCommand.Parameters.Add(new SqlParameter("@rowVersion", SqlDbType.BigInt, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, rowVersion));
            sqlCommand.Parameters.Add(new SqlParameter("@modelTypeCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, modelTypeCode));
            sqlCommand.Parameters.Add(new SqlParameter("@description", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, description));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId0", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId0));
            sqlCommand.Parameters.Add(new SqlParameter("@externalId1", SqlDbType.NVarChar, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, externalId1));
            // Update the record in the SQL database.
            sqlCommand.ExecuteNonQuery();
        }
        
        /// <summary>Collects the table lock request(s) for an Update operation</summary>
        /// <param name="adoTransaction">A list of locks required for this operation.</param>
        public static void Delete(AdoTransaction adoTransaction)
        {
            // These table lock(s) are required for the 'Delete' operation.
            adoTransaction.LockRequests.Add(new TableWriterRequest(ServerDataModel.ModelType));
            Model.ArchiveChildren(adoTransaction);
        }
        
        /// <summary>Inserts a ModelType record using Metadata Parameters.</summary>
        /// <param name="parameters">Contains the metadata parameters.</param>
        public static void Delete(ParameterList parameters)
        {
            // Extract the parameters from the command batch.
            AdoTransaction adoTransaction = parameters["adoTransaction"];
            SqlTransaction sqlTransaction = parameters["sqlTransaction"];
            long rowVersion = parameters["rowVersion"];
            int modelTypeCode = parameters["modelTypeCode"];
            // Call the internal method to complete the operation.
            ModelType.Delete(adoTransaction, sqlTransaction, rowVersion, modelTypeCode);
        }
        
        /// <summary>Deletes a ModelType record.</summary>
        /// <param name="transaction">Commits or rejects a set of commands as a unit</param>
        /// <param name="RowVersion">The version number of this row.</param>
        /// <param name="modelTypeCode">The value for the ModelTypeCode column.</param>
        /// <param name="archive">true to archive the object, false to unarchive it.</param>
        public static void Delete(AdoTransaction adoTransaction, SqlTransaction sqlTransaction, long rowVersion, int modelTypeCode)
        {
            // Accessor for the ModelType Table.
            ServerDataModel.ModelTypeDataTable modelTypeTable = ServerDataModel.ModelType;
            // Rule #1: Make sure the record exists before updating it.
            ServerDataModel.ModelTypeRow modelTypeRow = modelTypeTable.FindByModelTypeCode(modelTypeCode);
            if ((modelTypeRow == null))
            {
                throw new Exception(string.Format("The ModelType table does not have an element identified by {0}", modelTypeCode));
            }
            // Rule #2: Optimistic Concurrency Check
            if ((modelTypeRow.RowVersion != rowVersion))
            {
                throw new System.Exception("This record is busy.  Please try again later.");
            }
            // Delete the child records.
            for (int index = 0; (index < modelTypeRow.GetModelRows().Length); index = (index + 1))
            {
                ServerDataModel.ModelRow childModelRow = modelTypeRow.GetModelRows()[index];
                Model.DeleteChildren(adoTransaction, sqlTransaction, childModelRow.RowVersion, childModelRow.ModelId);
            }
            // Increment the row version
            rowVersion = ServerDataModel.RowVersion.Increment();
            // Delete the record in the ADO database.
            modelTypeRow[modelTypeTable.RowVersionColumn] = rowVersion;
            adoTransaction.DataRows.Add(modelTypeRow);
            modelTypeRow.Delete();
            // Delete the record in the SQL database.
            SqlCommand sqlCommand = new SqlCommand("update \"ModelType\" set \"IsDeleted\" = 1 where \"ModelTypeCode\"=@modelTypeCode");
            sqlCommand.Connection = sqlTransaction.Connection;
            sqlCommand.Transaction = sqlTransaction;
            sqlCommand.Parameters.Add(new SqlParameter("@modelTypeCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, modelTypeCode));
            sqlCommand.ExecuteNonQuery();
        }
        
        /// <summary>Collects the table lock request(s) for an Update operation</summary>
        /// <param name="adoTransaction">A list of locks required for this operation.</param>
        public static void Archive(AdoTransaction adoTransaction)
        {
            // These table lock(s) are required for the 'Archive' operation.
            adoTransaction.LockRequests.Add(new TableWriterRequest(ServerDataModel.ModelType));
            Model.ArchiveChildren(adoTransaction);
        }
        
        /// <summary>Inserts a ModelType record using Metadata Parameters.</summary>
        /// <param name="parameters">Contains the metadata parameters.</param>
        public static void Archive(ParameterList parameters)
        {
            // Extract the parameters from the command batch.
            AdoTransaction adoTransaction = parameters["adoTransaction"];
            SqlTransaction sqlTransaction = parameters["sqlTransaction"];
            long rowVersion = parameters["rowVersion"];
            int modelTypeCode = parameters["modelTypeCode"];
            // Call the internal method to complete the operation.
            ModelType.Archive(adoTransaction, sqlTransaction, rowVersion, modelTypeCode);
        }
        
        /// <summary>Archives a ModelType record.</summary>
        /// <param name="transaction">Commits or rejects a set of commands as a unit</param>
        /// <param name="RowVersion">The version number of this row.</param>
        /// <param name="modelTypeCode">The value for the ModelTypeCode column.</param>
        /// <param name="archive">true to archive the object, false to unarchive it.</param>
        public static void Archive(AdoTransaction adoTransaction, SqlTransaction sqlTransaction, long rowVersion, int modelTypeCode)
        {
            // Accessor for the ModelType Table.
            ServerDataModel.ModelTypeDataTable modelTypeTable = ServerDataModel.ModelType;
            // Rule #1: Make sure the record exists before updating it.
            ServerDataModel.ModelTypeRow modelTypeRow = modelTypeTable.FindByModelTypeCode(modelTypeCode);
            if ((modelTypeRow == null))
            {
                throw new Exception(string.Format("The ModelType table does not have an element identified by {0}", modelTypeCode));
            }
            // Rule #2: Optimistic Concurrency Check
            if ((modelTypeRow.RowVersion != rowVersion))
            {
                throw new System.Exception("This record is busy.  Please try again later.");
            }
            // Archive the child records.
            for (int index = 0; (index < modelTypeRow.GetModelRows().Length); index = (index + 1))
            {
                ServerDataModel.ModelRow childModelRow = modelTypeRow.GetModelRows()[index];
                Model.ArchiveChildren(adoTransaction, sqlTransaction, childModelRow.RowVersion, childModelRow.ModelId);
            }
            // Increment the row version
            rowVersion = ServerDataModel.RowVersion.Increment();
            // Delete the record in the ADO database.
            modelTypeRow[modelTypeTable.RowVersionColumn] = rowVersion;
            adoTransaction.DataRows.Add(modelTypeRow);
            modelTypeRow.Delete();
            // Archive the record in the SQL database.
            SqlCommand sqlCommand = new SqlCommand("update \"ModelType\" set \"IsArchived\" = 1 where \"ModelTypeCode\"=@modelTypeCode");
            sqlCommand.Connection = sqlTransaction.Connection;
            sqlCommand.Transaction = sqlTransaction;
            sqlCommand.Parameters.Add(new SqlParameter("@modelTypeCode", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, null, DataRowVersion.Current, modelTypeCode));
            sqlCommand.ExecuteNonQuery();
        }
    }
}
